name: monithor
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - plotly
  - matplotlib
  - scikit-learn
  - xgboost
  - polars
  - pyarrow
  - nbformat 
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8 
  - lightning
  - scikit-image
  - numba
  - pip:
    - folktables
    - ipympl
    - typer[all]
    - foolbox
    - timm
    - datasets 
    - transformers