[project]
authors = ["Augustin Godinot <augustin.godinot@inria.fr>"]
channels = ["conda-forge", "pytorch", "nvidia"]
description = "TODO"
name = "QuRD"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
hf-hub = "python scripts/hf_hub.py"

[dependencies]
python = "3.11.*"
pytorch = { version = ">=2.4.1", channel = "pytorch" }
torchvision = { version = ">=0.19", channel = "pytorch" }
torchmetrics = ">=1.4.2,<2"
huggingface_hub = ">=0.26.2"
polars = ">=1.9.0,<2"
scikit-image = ">=0.24.0,<0.25"
numba = ">=0.60.0,<0.61"
foolbox = ">=3.3.1,<4"
scipy = ">=1.14.1,<2"
setuptools = "*"
typer-slim = ">=0.13.0,<0.14"
ipykernel = "*"
pip = "*"
datasets = ">=2.19.2,<3"
scikit-learn = ">=1.5.2,<2"
plotly = ">=5.24.1,<6"
timm = ">=1.0.12,<2"

[feature.cpu.dependencies]
cpuonly = { version = ">=2.0", channel = "pytorch" }

[feature.cuda]
channels = ["nvidia", { channel = "pytorch", priority = -1 }]

[feature.cuda.dependencies]
pytorch-cuda = { version = "12.1.*", channel = "pytorch" }

[pypi-dependencies]
py-spy = ">=0.4.0, <0.5"

[environments]
cuda = ["cuda"]
default = ["cpu"]
