[project]
authors = ["Augustin Godinot <augustin.godinot@inria.fr>"]
channels = ["conda-forge", "pytorch"]
description = "TODO"
name = "maurice"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
hf-hub = "python hf_hub.py"

# [dependencies]
# python = "3.12.*"
# pytorch = { version = ">=2.4.1", channel = "pytorch" }
# torchvision = { version = ">=0.19", channel = "pytorch" }
# cpuonly = { version = ">=2.0", channel = "pytorch" }
# torchmetrics = ">=1.4.2,<2"
# huggingface_hub = ">=0.25.1,<0.26"
# polars = ">=1.9.0,<2"
# timm = ">=1.0.9,<2"
# # scikit-image = ">=0.24.0,<0.25"
# # numba = ">=0.60.0,<0.61"
# # foolbox = ">=3.3.1,<4"
# # scipy = ">=1.14.1,<2"
# setuptools = "*"
# typer = "*"

[dependencies]
python = "3.11.*"
pytorch = { version = ">=2.4.1", channel = "pytorch" }
torchvision = { version = ">=0.19", channel = "pytorch" }
cpuonly = { version = ">=2.0", channel = "pytorch" }
torchmetrics = ">=1.4.2,<2"
huggingface_hub = ">=0.25.1,<0.26"
polars = ">=1.9.0,<2"
timm = ">=1.0.9,<2"
scikit-image = ">=0.24.0,<0.25"
numba = ">=0.60.0,<0.61"
foolbox = ">=3.3.1,<4"
scipy = ">=1.14.1,<2"
setuptools = "*"
typer = "*"
