[project]
authors = ["Augustin Godinot <augustin.godinot@inria.fr>"]
channels = ["conda-forge", "pytorch", "nvidia"]
description = "TODO"
name = "QuRD"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
hf-hub = "python main.py hf_hub"
bench = "python main.py bench"

[dependencies]
python = ">=3.12.3,<3.13"
pytorch = { version = ">=2.5.1,<3", channel = "pytorch" }
torchvision = { version = ">=0.20.1,<0.21", channel = "pytorch" }
torchmetrics = ">=1.6.1,<2"
huggingface_hub = ">=0.28.0,<0.29"
polars = ">=1.22.0,<2"
scikit-image = ">=0.25.1,<0.26"
numba = ">=0.59.1,<0.60"
foolbox = ">=3.3.1,<4"
scipy = ">=1.15.1,<2"
setuptools = ">=75.8.0,<76"
typer-slim = ">=0.15.1,<0.16"
ipykernel = ">=6.29.5,<7"
pip = ">=25.0.1,<26"
datasets = ">=3.2.0,<4"
scikit-learn = ">=1.6.1,<2"
plotly = ">=6.0.0,<7"
timm = ">=1.0.14,<2"

[feature.cpu.dependencies]
cpuonly = { version = ">=2.0", channel = "pytorch" }

[feature.cuda]
channels = ["nvidia", { channel = "pytorch", priority = -1 }]

[feature.cuda.dependencies]
pytorch-cuda = { version = "12.1.*", channel = "pytorch" }

[pypi-dependencies]
py-spy = ">=0.4.0, <0.5"
python-dotenv = ">=1.0.1, <2"

[environments]
cuda = ["cuda"]
default = ["cpu"]
